### ISSUE TITLE
@bind not valid attribute

### ISSUE THREAD

**Issue by msaroka** [Aaltuj/VxFormGenerator#14]
I am trying out the Nuget 0.11 version and it is showing the label and laying out the grid just fine, but the control is not shown and the below error is generated in the output window.  I am using .NET 5.

System.AggregateException: One or more errors occurred. (InvalidCharacterError: Failed to execute 'setAttribute' on 'Element': '@bind' is not a valid attribute name.)
 ---> System.InvalidOperationException: InvalidCharacterError: Failed to execute 'setAttribute' on 'Element': '@bind' is not a valid attribute name.
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.InvokeRenderCompletedCallsAfterUpdateDisplayTask(Task updateDisplayTask, Int32[] updatedComponents)

**Comment by Aaltuj** [comment]
hi @msaroka could you provide a reproduction of your error.

**Comment by msaroka** [comment]
It took a while to find the combination of things that call this error.
Create a class that will be the model type of the EditForm.  One property must be a bool type.
Load the class in the OnInitializedAsync method of the form and assign it to the local field that is the model of the form
If the loaded object has a true value in the bool property the error will trigger.  it will not if it is false.

**Comment by Aaltuj** [comment]
Sorry, i was quite busy with other stuff. Great that you found the combination. I would love to help if you are able provide that code.

**Comment by msaroka** [comment]
In FeedingSession.cs change the line to:

public bool ThrowingUp { get; set; } = true;

This will cause the error.
