### ISSUE TITLE
Leveraging Description Attribute in Enums

### ISSUE THREAD

**Issue by msaroka** [Aaltuj/VxFormGenerator#19]
If an Enum uses the Description attribute could we control the text displayed in the dropdowns and multiple checkboxes?

Below is an example of what I mean.

    public enum FuelType
    {
        [Description("Bituminous Coal")] bit,
        [Description("Home Heating and Diesel Fuel (Distillate)")] dfo,
        [Description("Jet Fuel")] jf,
        [Description("Kerosene")] ker,
        [Description("Lignite Coal")] lig,
        [Description("Municipal Solid Waste")] msw,
        [Description("Natural Gas")] ng,
        [Description("Petroleum Coke")] pc,
        [Description("Propane Gas")] pg,
        [Description("Residual Fuel Oil")] rfo,
        [Description("Subbituminous Coal")] sub,
        [Description("Tire -Derived Fuel")] tdf,
        [Description("Waste Oil")] wo
    }

**Comment by Aaltuj** [comment]
This is supported by the display attribute.

https://github.com/Aaltuj/VxFormGenerator/blob/786fbc52e5667df5c727dd2202c3e615ab187852/VxFormGeneratorDemoData/VxFormLayoutAnnotated.cs#L34-L42

**Comment by msaroka** [comment]
Perfect.  Thank you.
