### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by PizzaConsole** [Aaltuj/VxFormGenerator#21]
Put a license on your project, there are loads of people that wont even get in a 10 mile radius of an unlicensed project on github

**Comment by Aaltuj** [comment]
The core has the LICENSE.
https://github.com/Aaltuj/VxFormGenerator/blob/master/VxFormGenerator.Core/LICENSE.txt

There are even nuget versions:
https://www.nuget.org/packages/VxFormGenerator.Core/0.4.0/License
https://www.nuget.org/packages/VxFormGenerator.Components.Bootstrap/0.4.0/License
https://www.nuget.org/packages/VxFormGenerator.Components.Plain/0.4.0/License

I'll move it to the root of the project, thanks for your constructive feedback.

**Comment by PizzaConsole** [comment]
Awesome, thank you very much!
