### ISSUE TITLE
Hide Control or group of controls dinamycally

### ISSUE THREAD

**Issue by marcoCasamento** [Aaltuj/VxFormGenerator#28]
Is it possible to hide a control (or a group of control) based on a value of a EditForm element ?
For example, imagine you have a form with a Combobox with values "Person", "Company".
If the user selects "Person", I have to show fields Firstname/Lastname whereas if user selects "Company" I have to show just "CompanyName".

thanks

**Comment by msaroka** [comment]
I had this issue with a project I was working on.  What I ended up doing was putting a toggle control on the page and two classes that inherited from the base class.  When the page was reloaded it pulled the correct inherited class as the data source for the form.

**Comment by marcoCasamento** [comment]
thanks for your input, but in my case is not applicable. 
I need that the input must be defined inside the poco not statically placed on the page, so that I can define a "rule" that hides or shows elements based on the value of another field in the same poco object.
