### ISSUE TITLE
Support LIsts of Objects with ability to add/remove items from the list

### ISSUE THREAD

**Issue by gizmohd** [Aaltuj/VxFormGenerator#32]
Should be able to support lists of custom objects..  With the ability to add and remove items from that list.

**Comment by Aaltuj** [comment]
Hi, could you elaborate on what you are requesting. Please provide an example and maybe i can help.

**Comment by Slyker** [comment]
He asked for an implémentation of list of class in your générator
Ex : List<Person> Persons
With a field where we can as/edit sélect/unsélect one or multiple élément
Would be a great thing
